# Base image: Node 22 LTS, Debian slim
FROM node:22-slim AS base

# Install dependencies
FROM base AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

# Build stage
FROM base AS builder
WORKDIR /app
ENV NODE_ENV=production
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npx prisma generate && npm run build

# Runtime image
FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production

# Non-root user
RUN useradd -m nextjs
USER nextjs

# Copy necessary assets from the standalone build
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000

# server.js is generated by Next.js standalone output
CMD ["node", "server.js"]
